version: 0.2

phases:
  install:
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade awscli
      - pip install boto3
      - pip install pytest
      - 

  pre_build:
    commands:
      - pwd
      - export PYTHONPATH=$PYTHONPATH:pwd
      - ls -la
      - echo $PATH
      - echo $PYTHONPATH
      - pytest tests -v
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml