version: 0.2

phases:
  install:
    commands:

      # Upgrade AWS CLI to the latest version
      - pip install --upgrade pip
      - pip install --force-reinstall --upgrade awscli
      - pip install boto3
      - pip install pytest
      - 

  pre_build:
    commands:
      - python -m pytest tests -v
  
  build:
    commands:

      # Use AWS SAM to package the application by using AWS CloudFormation
      #- aws --region ap-northeast-1 cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

  post_build:
    commands:
      #- aws --region ap-northeast-1 cloudformation deploy --template-file template-export.yml --stack-name cloud9-myCodeStar
      - aws cloudformation deploy --template-file template-export.yml --stack-name cloud9-myCodeStar


artifacts:
  type: zip
  files:
    - template-export.yml