AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

#Parameters:
#  ProjectId:
#    Type: String
#    Description: CodeStar projectId used to associate new resources to team members
# Enable blue/green deployments using this Globals section. For instructions, see the AWS CodeStar User Guide:
# https://docs.aws.amazon.com/codestar/latest/userguide/how-to-modify-serverless-project.html?icmpid=docs_acs_rm_tr
#
#Globals:
#   Function:
#     AutoPublishAlias: live
#     DeploymentPreference:
#       Enabled: true
#       Type: Canary10Percent5Minutes

Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  myFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Role: 'arn:aws:iam::527443923623:role/myAdminRole'
      CodeUri: ./
      ReservedConcurrentExecutions: 1
      Events:
        AnyEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
        TopEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
      Environment:
        Variables:
          BUCKET_NAME: "samplebucket-suzuki"
          HEROES_JSON_KEY: "dataset/heroes/Annotations/sample.json"